list p=16f876
#include<p16f876.inc>
	org 0x00
		debut clrw
			;MOVE TO BANK 1
			; TRISC = 0x00
			BSF STATUS , RP0
			BCF STATUS , RP1
			;CLEAR TRISC
			CLRF TRISC
			;TRISB = 0xFF
			MOVLW 0xFF
			MOVWF TRISB
			;MOVE TO BANK 0
			BCF STATUS , RP0
			BCF STATUS , RP1

MAIN
			;TEST FOR START BUTTON
BTN_START	BTFSS PORTB , 1
			GOTO STOP_MOTOR
			;TEST FOR REVERSE BUTTON
			MOVLW 0x28
BTN_REVERSE	BTFSS PORTB , 4
			GOTO REVERSE
START_MOTOR
			MOVLW 0x08
			MOVWF PORTC
			GOTO MAIN
REVERSE	 	MOVLW 0x20
			MOVWF PORTC
			GOTO MAIN
STOP_MOTOR	MOVLW 0x00
			MOVWF PORTC
			GOTO MAIN

END